version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - pip install aws-sam-cli
      - npm install
  build:
    commands:
      - npm run build
      - npm test
      - sam --version
      - mkdir .out
      - sam package --template-file template.yml --s3-bucket ${STAGING_BUCKET_PREFIX}-${AWS_REGION} --output-template-file .out/packaged.yaml
      # FIXME - parse the version from the package.json
      - aws s3 cp .out/packaged.yaml s3://${STAGING_BUCKET_PREFIX}-${AWS_REGION}/1.5.0/template.yml
  post_build:
    commands:
      - sam publish --template .out/packaged.yaml --region ${AWS_REGION}
      - sam publish --template .out/packaged.yaml --region us-east-1
