AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Create service-health-metrics based on cloudwatch alarms."

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mechanicalrock-ops-metrics
    Description: Creating service-health-metrics based on cloudwatch alarms.
    Author: Mechanical Rock
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["metrics", "mttr", "mtbf"]
    HomePageUrl: https://github.com/MechanicalRock/aws-ops-metrics
    SemanticVersion: 1.1.0
    SourceCodeUrl: https://github.com/MechanicalRock/aws-ops-metrics

Resources:
  DescribeAlarmPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: cloudwatch:DescribeAlarmHistory
            Resource: "*"

  MTTREventHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Create CloudWatch mttr metric from cloudwatch alarm events
      Handler: mttr.handler
      Runtime: nodejs12.x
      CodeUri: .build/src
      Events:
        cloudwatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.cloudwatch"
              detail-type:
                - "CloudWatch Alarm State Change"
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - !Ref DescribeAlarmPolicy

  MTBFEventHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Create CloudWatch mtbf metric from cloudwatch alarm events
      Handler: mtbf.handler
      Runtime: nodejs12.x
      CodeUri: .build/src
      Events:
        cloudwatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.cloudwatch"
              detail-type:
                - "CloudWatch Alarm State Change"
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - !Ref DescribeAlarmPolicy

  MTTFEventHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: Create CloudWatch mttf metric from cloudwatch alarm events
      Handler: mttf.handler
      Runtime: nodejs12.x
      CodeUri: .build/src
      Events:
        cloudwatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.cloudwatch"
              detail-type:
                - "CloudWatch Alarm State Change"
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - !Ref DescribeAlarmPolicy

  OpsDashboardGenerator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Build OPS Trend dashboard from CloudWatch metrics
      Handler: dashboardHandler.generateDashboardTrend
      Runtime: nodejs12.x
      CodeUri: .build/src
      Timeout: 60
      Events:
        DashboardEventRule:
          Type: Schedule
          Properties:
            Schedule: "cron(*/5 * * * ? *)"
      Policies:
      - CloudWatchDashboardPolicy: {}
